import type { Metadata } from "next";
import {DM_Sans, Space_Grotesk} from "next/font/google"
import "./globals.css";
import Footer from "./_components/Footer";


export const metadata: Metadata = {
  title: "Jeko",
  description: "Generated by create next app",
};

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm_sans',
})
 
const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space_grotesk',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dm_sans.variable} ${space_grotesk.variable}`}>
      <body>{children}
        <Footer/>
      </body>
    </html>
  );
}
